### ISSUE TITLE
doesn't work with x64

### ISSUE THREAD

**Issue by wilzbach** [adamdruppe/adrdox#1]
Hey @adamdruppe,

I run into a couple of small problems when compiling on x64 - you can replicate this by compiling with `-m64`. I just quickly fixed it (didn't had so much time) by ugly casting, but if you want I can send you a proper PR ;-)

**Comment by adamdruppe** [comment]
On Sun, Apr 24, 2016 at 03:18:40AM -0700, Sebastian Wilzbach wrote:
> I run into a couple of small problems when compiling on x64 - you can replicate this by compiling with `-m64`. I just quickly fixed it (didn't had so much time) by ugly casting, but if you want I can send you a proper PR ;-)

Try it now, I rarely actually use 64 bit and forget about those
size_t things a lot!

**Comment by wilzbach** [comment]
> Try it now

Thanks a lot for the fix - works now :)
