### ISSUE TITLE
error caused by alias to lambda

### ISSUE THREAD

**Issue by Laeeth** [adamdruppe/adrdox#18]
https://github.com/kaleidicassociates/nanomsg-wrapper/blob/master/source/nanomsg/bindings.d
line 229: alias NN_CMSG_ALIGN_ = (len) => (len + size_t.sizeof - 1) & cast(size_t) ~(size_t.sizeof - 1);
line 233: alias NN_CMSG_FIRSTHDR = (mhdr) => nn_cmsg_nxthdr_ (cast(nn_msghdr*) mhdr, null);
line 235: alias NN_CMSG_NXTHDR = (mhdr, cmsg) => nn_cmsg_nxthdr_ (cast(nn_msghdr*) mhdr, cast(nn_cmsghdr*) cmsg);
line 237: alias NN_CMSG_DATA = (cmsg) => cast(ubyte*) ((cast(nn_cmsghdr*) cmsg) + 1);
line 241: alias NN_CMSG_SPACE = (len) => (NN_CMSG_ALIGN_ (len) + NN_CMSG_ALIGN_ (nn_cmsghdr.sizeof));
line 243: alias NN_CMSG_LEN = (len) => (NN_CMSG_ALIGN_ (nn_cmsghdr.sizeof) + (len));
line 461: warns on the C-style semicolon following struct declaration
struct nn_socktype {
    int domain;
    int protocol;
    int flags;
    int function(void *hint, nn_sockbase **sockbase) create;
    int function(int socktype) ispeer;
    nn_list_item* item;
};
similarly (warns) on 507, 562, 754.

#dmd -of/var/www/dpldocs.info/locate locate.d  dom.d stemmer.d  cgi -J. -version=fastcgi -m64 -debug
First pass processing /fastssd/kaleidic/opensource/nanomsg-wrapper/source/nanomsg/bindings.d
bindings.d(229:24)[error]: Basic type, type constructor, symbol, or typeof expected
bindings.d(229:30)[error]: Declaration expected
bindings.d(229:59)[error]: Declaration expected
bindings.d(229:75)[error]: Expected this instead of (
bindings.d(229:94)[warn]: Empty declaration
bindings.d(233:26)[error]: Basic type, type constructor, symbol, or typeof expected
bindings.d(233:33)[error]: Declaration expected
bindings.d(233:74)[error]: Declaration expected
bindings.d(233:81)[warn]: Empty declaration
bindings.d(235:24)[error]: Basic type, type constructor, symbol, or typeof expected
bindings.d(235:37)[error]: Declaration expected
bindings.d(235:78)[error]: Declaration expected
bindings.d(235:102)[error]: Declaration expected
bindings.d(235:103)[warn]: Empty declaration
bindings.d(237:22)[error]: Basic type, type constructor, symbol, or typeof expected
bindings.d(237:29)[error]: Declaration expected
bindings.d(237:45)[error]: Declaration expected
bindings.d(237:69)[error]: Declaration expected
bindings.d(237:71)[error]: Declaration expected
bindings.d(237:75)[warn]: Empty declaration
bindings.d(241:23)[error]: Basic type, type constructor, symbol, or typeof expected
bindings.d(241:29)[error]: Declaration expected
bindings.d(241:54)[error]: Declaration expected
bindings.d(241:90)[error]: Declaration expected
bindings.d(241:91)[warn]: Empty declaration
bindings.d(243:21)[error]: Basic type, type constructor, symbol, or typeof expected
bindings.d(243:27)[error]: Declaration expected
bindings.d(243:66)[error]: Declaration expected
bindings.d(243:73)[error]: Declaration expected
bindings.d(243:74)[warn]: Empty declaration
bindings.d(461:2)[warn]: Empty declaration
bindings.d(507:2)[warn]: Empty declaration
bindings.d(562:2)[warn]: Empty declaration
bindings.d(754:2)[warn]: Empty declaration
First pass processing /fastssd/kaleidic/opensource/nanomsg-wrapper/source/nanomsg/package.d
First pass processing /fastssd/kaleidic/opensource/nanomsg-wrapper/source/nanomsg/wrap.d
Generating HTML for nanomsg
Listing nanomsg.bindings
Listing nanomsg
Listing nanomsg.wrap
Generating search for nanomsg.bindings
Generating search for nanomsg
Generating search for nanomsg.wrap
Writing search...

**Comment by adamdruppe** [comment]
I'm sorry, I never noticed the issues tab on this

**Comment by adamdruppe** [comment]
But this is fixed in the latest version. The parser didn't understand a few newer D keywords.
