### ISSUE TITLE
Feature request: output documentation for private structs

### ISSUE THREAD

**Issue by bachmeil** [adamdruppe/adrdox#21]
Sometimes I create structs for use only within a module that I would like documented. I would still like to document them both for my use during development and because others may want to understand what is going on.

**Comment by adamdruppe** [comment]
That's technically very easy to do (I was thinking of adding a switch for it anyway), but how would we want to configure if we want it for a package or not? I think we will need to make a config file thing like dpldocs.json file to put in there too.

**Comment by bachmeil** [comment]
I've only been testing this for single files so far, so I don't have an opinion. But how would it be helpful for a package?

**Comment by adamdruppe** [comment]
I added the switch to the generator, but still no way to set it from the automatic download...

**Comment by bachmeil** [comment]
Thanks. I've now had a chance to try the new version, and it works. I'm going to close this.

**Comment by adamdruppe** [comment]
oh i mixed up my own repositories! Where are you hosting btw? I wanna see!!

**Comment by bachmeil** [comment]
It's not quite done yet. I hadn't ever gotten around to documenting it because I don't care for ddoc. I had been using a documentation generator I wrote for R code instead. I tested out adrdox, and the latest version worked well, so I decided to try it out for this project. The project is embedr, which allows embedding an R interpreter inside a D program, or calling D functions from R. The repo is here:
https://bitbucket.org/bachmeil/embedr

I will post a comment here when it's up.

**Comment by adamdruppe** [comment]
On Mon, Mar 05, 2018 at 02:37:13PM -0800, Lance Bachmeier wrote:
> It's not quite done yet. I hadn't ever gotten around to documenting it because I don't care for ddoc.

Ah yes, I know how that goes :)

> I had been using a documentation generator I wrote for R code instead. I tested out adrdox, and the latest version worked well, so I decided to try it out for this project. The project is embedr, which allows embedding an R interpreter inside a D program, or calling D functions from R. The repo is here:
> https://bitbucket.org/bachmeil/embedr

Cool.

But thanks! Let me know if there's anything else you need added or changed or anything. I won't add something I outright *hate*, but other than that I'm pretty flexible and can help on a lot of things.

**Comment by bachmeil** [comment]
I don't have time to make a nice site right now, but you can view the initial version of the docs for my project [here](https://embedr.netlify.com/doc/embedr.html).
