### ISSUE TITLE
standard file 'skeleton-default.html' not found!

### ISSUE THREAD

**Issue by FreeSlave** [adamdruppe/adrdox#23]
Running doc2 from other place like this `doc2 --skeletion ../adrdox/skeleton.html` gives that error that skeleton-default.html not found. I'm not sure why it's even needed, I thought it's just a template for skeleton.html. But if it's needed how do I specify path to it?

**Comment by FreeSlave** [comment]
> But check this out, you wrote: `--skeletion`

My fault. But probably doc2 should not accept options it does not know.

Now with right option it gives me another error `standard file 'style.css' not found!`
And I'm don't know how to specify path to this too.
Maybe doc2 should have option like --standardFilesRoot to automatically find all standard files in the provided directory.

**Comment by katyo** [comment]
I added command line argument `--data-dir` in #43.
Also environment variable `ADRDOX_DATA_DIR` can be used to do same.

**Comment by katyo** [comment]
@FreeSlave can we close this issue?

**Comment by FreeSlave** [comment]
@katyo yep. But the message `Unable to determine data directory.` probably should include the hint about using --data-dir parameter. Otherwise it's ok. Closing.
