### ISSUE TITLE
static foreach

### ISSUE THREAD

**Issue by John-Colvin** [adamdruppe/adrdox#28]
seems to always generate errors like `'if' or 'assert' expected.

**Comment by adamdruppe** [comment]
Yeah, I need to update the parser.

**Comment by adamdruppe** [comment]
Hey, sorry for the long delay, but the master branch I *think* is now fixed for this. Can you recompile and try again? Or are you using the dpldocs hosted version? (I can update that too but it will be a couple more days. lol as a newlywed my time for open source hacking is exceedingly limited right now)
