### ISSUE TITLE
Add a release

### ISSUE THREAD

**Issue by FFY00** [adamdruppe/adrdox#31]
adrdox is used to generate documentation for relevant projects, like GtkD. This adds a need for it to be packaged by distributions. For this reason it should start having releases so that it could be packaged properly.

**Comment by adamdruppe** [comment]
Why can't distributions version it themselves since they're the ones doing the packaging too?

**Comment by FFY00** [comment]
The versioning should come from the upstream. It would be really chaotic having, for example, adrdox v1.5.0 in Archlinux and adrdox v0.9.8 in Debian. It doesn't really make sense for the downstream to choose the version. I guess we could package specific commits but that still isn't optional as it would make up to the distributions to choose when it is due an update.

**Comment by adamdruppe** [comment]
I guess that makes sense. Just my policy is to avoid breaking things at all, unless it was already broken, and I manage all my own dependencies so it tends to just work if you build it at any time (though part of the makefile mentions paths on my computer lol). I haven't even put this on the dub thing.

I could do a git tag thing like dub uses though. But it is totally arbitrary when it would be tagged, I have no formal process and do not intend to ever have one.

**Comment by chloekek** [comment]
I was actually working on adding adrdox to Nixpkgs!

If this makes it in soon then I can use the version number instead of a date in https://github.com/NixOS/nixpkgs/pull/62739 (I’ll try to get that one merged this weekend).

If not that’s fine too, just FYI. :)

**Comment by adamdruppe** [comment]
Well, tell me what you need and I'll make it happen. Is `git tag 'v1.0.0'` good enough for your purposes?

**Comment by FFY00** [comment]
You don't have to have a formal process, just add a tag when the improvements become relevant or for bugfixes.

Same, I am packaging this for Archlinux.

**Comment by FFY00** [comment]
Yes, adding a `v1.0.0` tag is perfectly fine :grin:.

**Comment by adamdruppe** [comment]
all right, there it is.

**Comment by chloekek** [comment]
Yeah, any version number is fine by me. Nixpkgs doesn’t enforce semver. Something that monotonically increases would be nice.

**Comment by FFY00** [comment]
Thank you!
