### ISSUE TITLE
Cross-reference to D identifier produces incorrect links in package.d

### ISSUE THREAD

**Issue by jondegenhardt** [adamdruppe/adrdox#35]
In one of my `package.d` files I have a LIST with links to the important functions, classes, etc. This has always produced good valid links. I just tried building locally with the current master branch of adrdox and the file names produced are incorrect. It looks like the correct file names have changed, but not the links.

Example (from: [tsv_utils/common/package.d](https://github.com/eBay/tsv-utils/blob/master/common/src/tsv_utils/common/package.d)):
```
$(LIST
    * [tsv_utils.common.utils.InputFieldReordering] - A class that creates a reordered
      subset of fields from an input line. Used to operate on a subset of fields in the
      order specified on the command line.
    * [tsv_utils.common.utils.BufferedOutputRange] - An OutputRange with an internal
      buffer used to buffer output. Intended for use with stdout, it is a significant
      performance benefit.
)
```
In my local `generate-docs/tsv_utils.common.html` file, this produces links to:
* `generated-docs/tsv_utils.common.utils.InputFieldReordering.html`
* `generated-docs/tsv_utils.common.utils.BufferedOutputRange.html`

However, the files have the names:
* `generated-docs/tsv_utils.common.utils._Input_Field_Reordering.html`
* `generated-docs/tsv_utils.common.utils._Buffered_Output_Range.html`

The underscores in the file names appears to be new. This file has been on the dpldocs server for a while, there the generated file names do not have the underscores. See: [tsv-utils.dpldocs.info/tsv_utils.common.html](https://tsv-utils.dpldocs.info/tsv_utils.common.html).

So far I haven't found this issue with references elsewhere in the `generated-docs` files, though I haven't gone through all the links. So it could be related to being in the `package.d` file.

**Comment by adamdruppe** [comment]
Yeah, the underscores are new, it was a response to me having trouble with case-insensitive filesystems causing conflicts.

But `--case-insensitive-filenames` isn't supposed to be set unless you specified it so could be a bug in here where I messed up the flag.

**Comment by adamdruppe** [comment]
ooooooooh

```

version(linux)
        __gshared bool caseInsensitiveFilenames = false;
else
        __gshared bool caseInsensitiveFilenames = true;
```

so it defaults to true on Windows, that is probably contributing to you seeing a difference here.

**Comment by adamdruppe** [comment]
and I think the link isn't going through because if the other modules aren't part of the "build", it doesn't actually look things up - it just passes through what you wrote between the `[]`.

Try doing `doc2 --load path/to/project package.d` or do the whole directory at once and I suspect it will pick it up...

**Comment by jondegenhardt** [comment]
I'm building on macOS. Perhaps your version specifier should be `Posix` rather than `linux`?

**Comment by adamdruppe** [comment]
I actually thought Mac was case-insensitive too......

**Comment by jondegenhardt** [comment]
macOS is a Unix. It's not case sensitive. But it's not linux. I think it's a BSD offshoot, but I don't remember.

**Comment by adamdruppe** [comment]
eeeeh i just tried:

```
cat A > A
cat a > a
cat a
```

and it gave A. Which means the file will be overwritten when it differs only in case, so it shares the same problem in this sense as Windows...

**Comment by jondegenhardt** [comment]
Oh. How did I not know this? Sorry about that.

**Comment by adamdruppe** [comment]
so it should work if you do the --load thing here since then it will look up, but regardless i should at least try to fix the bug anyway even if the symbols aren't fully loaded.....

**Comment by jondegenhardt** [comment]
Having trouble getting the --load command to do the right thing. Normally I use:
```
./doc2 path/to/tsv-utils
```
Running:
```
./doc2 --load path/to/tsv-utils path/to/project path/to/tsv-utils/common/src/tsv-utils/common/package.d
```
This built, but the most of the files normally produced are absent from the `generated-docs` directory.

**Comment by adamdruppe** [comment]
Yeah, --load makes it process them but not output the files...

If you normally do path/to/tsv-utils that should work....... that loads everything at once so all links.


I can reproduce locally though, gonna see if I can find the bug.

**Comment by jondegenhardt** [comment]
I also tried:
```
/doc2 --case-insensitive-filenames=false path/to/tsv-utils/
```
This appears to do the right thing, at least looking at a few of the links. This is probably good enough for my current purposes. I'm mainly checking that when I produce the next release and update `dlpdocs`, that the `dlpdocs` site is not broken.

**Comment by adamdruppe** [comment]
The dpldocs.info site uses Linux so it will work there the same as before anyway.

But I see what's happening in the name lookup: the package.d file doesn't actually import any modules, so the namespace lookup goes nowhere. Thus it falls back to just slapping `.html` at the end  of the given thing and hoping it works lol

**Comment by jondegenhardt** [comment]
Ah, so it is specific to package.d. LOL. I thought that was very odd when I saw it!

**Comment by adamdruppe** [comment]
yeah, it isn't package.d per se, it just tries to look up `[name]` following the D rules which strictly requires `import` statements in all modules including package.d.

If not, the lookup returns null and the link system then leaves it alone which works fine when it isn't mangling names for case.

**Comment by adamdruppe** [comment]
the relevant code:

```
                else if(auto c = text in allClasses) {
                        // classes may be thrown and as such can be referenced externally without import
                        // doing this as kinda a hack.
                        text = (*c).link;
                } else
                        text ~= ".html";
```

so i think i'll just throw in the case sensitive hack in there and probably be good enough

**Comment by jondegenhardt** [comment]
Oh, should really have import statements in the package.d file?

I guess it hasn't affected any of my code because my code always imports specific modules underneath `common`, and never the entire package. The main reason the `package.d` file exists is to create a place to put documentation for adrdox/dlpdocs!

Anyway, if its the correct thing for adrdos/dlpdocs, I can add import statements.

**Comment by jondegenhardt** [comment]
Just pulled your commit, that seems to fix it.

**Comment by adamdruppe** [comment]
Yea, if you look down many of the Phobos package.d you will see a list of `public import` statements that bring in the submodules. Without that, importing the top-level thing doesn't really do much; none of the child modules are actually imported.

But yeah I tend to not use package.d either except for docs too. So while technically you are supposed to import names to use them in D or in adrdox, the new commit basically handles it too. I'd say good enough the way it is now if it works for you.

**Comment by jondegenhardt** [comment]
Hey, thanks for such an amazingly quick response. You've always been quick to respond, so perhaps I shouldn't be surprised, but this level of help is not the norm! And it certainly made my day simpler, so thanks!

**Comment by adamdruppe** [comment]
you just caught me online :P (I'm actually on a video call for a nonprofit I participate with. Pretty mindless tbh, I have nothing to add to the meeting so just idly listening in while looking at my email. good for multitasking attention)
