### ISSUE TITLE
Inconsistant comment parsing between struct/classes and their members.

### ISSUE THREAD

**Issue by SealabJaster** [adamdruppe/adrdox#36]
Example adrdocs: https://jcli.dpldocs.info/jaster.cli.text.TextBufferWriter.html

If you have a look at the [implementation](https://jcli.dpldocs.info/source/jaster.cli.text.d.html#L645), the struct and its functions are written in the same comment style, but only the struct's documentation is showing up properly. All of its member functions' documentation isn't being split up correctly (except for the single lined `///` ones).

**Comment by adamdruppe** [comment]
On Sat, Aug 01, 2020 at 05:42:44PM -0700, Bradley Chatha wrote:
> If you have a look at the [implementation](https://jcli.dpldocs.info/source/jaster.cli.text.d.html#L645), the struct and its functions are written in the same comment style, but only the struct's documentation is showing up properly. All of its member functions' documentation isn't being split up correctly.

OK, yeah, I see it, the leading indentation is throwing off the
detection of the thing. It is such a pain to reliably detect these
purely decorative things without confusing them with list markers.

I'll see if I can fix it tomorrow.

**Comment by adamdruppe** [comment]
You have no idea how badly I want to say "that leading thing is unsupported" lol.

But I think I fixed it on my test version: http://dpldocs.info/experimental-docs/jaster.cli.text.TextBufferWriter.fill.html

just gotta ensure no regression in other projects and I can push it live.

**Comment by adamdruppe** [comment]
```
    /**
        $(LIST
            * cool
     * omg
        )
    */
```

change one space on that omg line and it can be considered part of the cool list item.

yikes.

but i think i have it passing ........

**Comment by adamdruppe** [comment]
And it is pushed live now, lemme know if you can confirm fixed or see other problems.

**Comment by SealabJaster** [comment]
Looks good to me now, thanks, especially for how fast it was!

Blame the old Mono-D for the weird leading spam, it kind of rubbed off on me (at least... I think it was from Mono-D o.o).

Thanks again.
