### ISSUE TITLE
`findStandardFile` does not works proper when running adrdox by dub run

### ISSUE THREAD

**Issue by katyo** [adamdruppe/adrdox#37]
When I run __adrdox__ using `dub run` it fails:

```
$ dub run adrdox -- -i -o adoc uctl
Building package adrdox in /home/kayo/.dub/packages/adrdox-2.3.1/adrdox/
Performing "debug" build using dmd for x86_64.
adrdox 2.3.1: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Copying files for adrdox...
Running ../../../.dub/packages/adrdox-2.3.1/adrdox/build/adrdox -i -o adoc uctl
object.Exception@../../../.dub/packages/adrdox-2.3.1/adrdox/doc2.d(66): standard file 'search-docs.js' not found!
----------------
../../../.dub/packages/adrdox-2.3.1/adrdox/doc2.d:66 @safe immutable(char)[] adrdox.main.findStandardFile!(true).findStandardFile(immutable(char)[]) [0xa5d40e]
../../../.dub/packages/adrdox-2.3.1/adrdox/doc2.d:80 @safe void adrdox.main.copyStandardFileTo!(true).copyStandardFileTo(immutable(char)[], immutable(char)[]) [0xa7a780]
../../../.dub/packages/adrdox-2.3.1/adrdox/doc2.d:3592 _Dmain [0xa2ff56]
Program exited with code 1
```

As I assume it's so because `thisExePath` is "../../../.dub/packages/adrdox-2.3.1/adrdox/build/adrdox" in that case:

https://github.com/adamdruppe/adrdox/blob/d5ee8a2db8b240af1fbd826b7b78362525ddd19f/doc2.d#L63

So one extra `.dirName` call is needed to get proper path prefix (i.e. `thisExePath.dirName.dirName` instead of `thisExePath.dirName`).

**Comment by adamdruppe** [comment]
oh yeah I saw that before once but never thought about fixing it. thanks!

**Comment by katyo** [comment]
Hmm... It seems `search-docs.js` just is not listed in "copyFiles" field in _dub.json_.

**Comment by katyo** [comment]
I think we need a proper way to lookup directory where shared files located.
Usually configuration variables like `DATA_DIR` is used for this purposes.
I little bit newbie in D so I don't know how configuration variables can be provided to code at compile time.
Or maybe this is reasonable to import resource files directly to executable to writing its instead of copying.

**Comment by adamdruppe** [comment]
`import`ing files into the exe makes it a bit harder to customize them. But.... since it writes out a copy it is still possible though so that might be ok.

**Comment by katyo** [comment]
As I see currently _search-docs.html_ is imported to executable:
https://github.com/adamdruppe/adrdox/blob/8119455471da989aa12361349c5fab372ea91240/doc2.d#L3997

**Comment by katyo** [comment]
Still I think the copy is most efficient especially for copy-on-write filesystems.

I assume we can simply determine data directory once on running.
We can simply try those paths to lookup _script.js_:
1. `thisExePath.dirName`
    Resources located in same directory with executable.
2. `thisExePath.dirName.dirName`
    Resources can be found in parent directory of executable directory.
3. `thisExePath.dirName.dirName ~ "/share/adrdox"`
    When executable located in "$PREFIX/bin/adrdox" then resources can be found in "$PREFIX/share/adrdox".
