### ISSUE TITLE
add --include option for a main page

### ISSUE THREAD

**Issue by wilzbach** [adamdruppe/adrdox#5]
It would be quite cool to have a main page to which one can link.

In other documentation engines this is solved by having an `--include` option which allows to include a special index file just for the documentation.

**Comment by adamdruppe** [comment]
What do you mean here? Like an `index.html`? You can do a `package.d` with documentation too...

**Comment by wilzbach** [comment]
I am not sure what I meant. It's been a long time ago. Sorry.
