### ISSUE TITLE
Only one linkage type should be displayed per declaration

### ISSUE THREAD

**Issue by pbackus** [adamdruppe/adrdox#52]
When multiple linkage attribute declarations are nested, dpldocs currently displays all of them instead of just the most-nested one.

For example, the signature of [`GC.inFinalizer`][1] is rendered like this:

```
extern (C) extern (D) extern (C) extern (D) extern (C) pragma(mangle, "gc_inFinalizer") static nothrow @nogc @safe
bool inFinalizer()
```

...because it is preceded by multiple `extern(C):` and `extern(D):` declarations.

[1]: https://druntime.dpldocs.info/core.memory.GC.inFinalizer.html

**Comment by adamdruppe** [comment]
aaah yeah i should only keep the last one on the list

**Comment by adamdruppe** [comment]
that fixes it, pushing the new thing now (which is surprisingly slow, the ldc optimize build i deploy takes a couple minutes to compile, then the site needs to rebuild druntime!)

**Comment by adamdruppe** [comment]
and it is up.
