### ISSUE TITLE
trim unittest block for empty lines at start and end

### ISSUE THREAD

**Issue by wilzbach** [adamdruppe/adrdox#7]
... or submit a PR to fix it to Phobos ;-)

Spotted here:

http://dpldocs.info/experimental-docs/std.ascii.isAlphaNum.html

**Comment by adamdruppe** [comment]
Huh, 2 years later, but fixed!

https://github.com/adamdruppe/adrdox/commit/f16090cc3a41d981af0b4dd19e80f2fdf6d22e4d
